### ISSUE TITLE
Unsound transmutation of `repr(Rust)` types

### ISSUE THREAD

**Issue by LegionMammal978** [CeleritasCelery/rune#11]
Several functions in this crate transmute integers to and from `Data`-containing enums. However, this is unsound, since both `Data` and the enums containing it are `repr(Rust)`, which has no layout guarantees. To fix this, additional `repr` attributes must be added:

* In `src/object/data.rs`, `Data` must have `#![repr(transparent)]`.
* In `src/object/mod.rs`, `Object` must have `#![repr(u8, align(8))]`.
* In `src/object/sub_type.rs`, `FuncCell` must have `#![repr(u8, align(8))]`.
* In `src/object/sub_type.rs`, `IntOrMarker` must have `#![repr(C)]`.
* In `src/object/sub_type.rs`, `Number` must have `#![repr(u8, align(8))]`.

Also, `Data::from_raw()` should really be marked `unsafe`. For a `Data<&'a T>` value to be valid, its `data` must be derived from an `&'a T` reference, and `Data::from_raw()` is unable to check this. Three new `unsafe` blocks should be added to the call sites: `UNUSED`, which is sound since a `Data<()>` is always valid; `Data::<&'a T>::from_ref()`, which is sound since `ptr` is derived from an `&'a T` reference; and `Data::<i64>::from_int()`, which is sound since a `Data<i64>` is always valid.

Finally, I have a minor question: Why is `LCellOwner::new()` marked `unsafe`? Is there any unchecked precondition or invariant it depends on?

**Comment by CeleritasCelery** [comment]
Thanks for opening an issue!

You are right about he missing repr's. Those will need to updated. I thought the `align(8)` repr was enough, but the doesn't seem to be the case.

The reason `Data::from_raw()` was not marked `unsafe` is because it's a private function. But you are correct that I should mark that function explicitly. 

`LCellOwner::new()` was marked `unsafe` because it initially took a [generativity::Id](https://github.com/CAD97/generativity/blob/1d4c09673a692937d69e912bb83e26070a9a7804/src/lib.rs#L9-L11) to set the lifetime `'id`. Since `Id` is Copy, you could have mulitple `LCellOwners` with a shared generative lifetime, which would obviously be unsound. But I realized I was using the API wrong and I am now taking a `generativity::Guard`, which is not `Copy`. So that function is safe. In fact you made me realize that I can get rid of the macro `make_lcell_owner` since it safe to call `new` directly.

**Comment by LegionMammal978** [comment]
> Edit: Actually I am not sure if `from_raw` should be `unsafe`. In the same way that getting a raw pointer from a reference is not `unsafe`, it seems like creating a `Data` from raw bits is not unsafe. It's when we actually try and create a new valid reference from `Data` that seems like it should be the `unsafe` part. And right now it is.

That is also a valid option, but I don't believe that it really helps us here. If we add the validity requirement that `Data<&'a T>` must always point to an `&'a T` (much like how `str` must always be valid UTF-8), then we only have to add `unsafe` blocks to the three call sites, all of which are trivially sound (and we must also be careful with the `transmute`s). But if it is allowed to hold an arbitrary `[u8; 7]`, then the `TryFrom` impls created by `define_unbox!()` in `src/macros.rs` become unsound, since we cannot prove at that point that an `Object`'s data is actually valid. Similarly, every other method that reads a `T` from a `Data<T>`, or an `Object`, or one of the subtypes must become `unsafe`, since there is no longer a requirement that a real `T` is present.

This is why `into_raw()` should be the `unsafe` method. Currently, there are only three public places that create a `Data` without `transmute`: `Data::UNUSED`, `Data::<&'a T>::from_ref()`, and `Data::<i64>::from_int()`. Since we already cannot create a `Data<&'a T>` without an `&'a T`, the simplest solution by far is to add that as a validity requirement to the type. That way, it is completely safe for anyone to convert it back.

Also, I've been looking at the rest of the codebase, and it's difficult to determine what an actual soundness bug should look like. Everything is at most `pub(crate)`, so there's no real adversarial "outside" to inspect the interfaces from; one can always postulate a crate-wide validity requirement preventing some part from being abused. It's also tough to evaluate the code in general, since many of the `unsafe` parts depend on clever invariants with few to no comments explaining why they should hold. (Also, some parts are explicitly workarounds to prevent Miri from complaining: in my experience, Miri can and does start yielding false negatives when you try to trip it up, so getting it to pass all the tests doesn't necessarily mean the code has no UB.)

P.S. In your blog post, you were wondering if there could be an `AliasCell` that allowed shared mutable access through `&mut` references. However, such an `AliasCell` has always been and will always be UB to use. By definition, an `&mut` reference is a *unique* reference, and the ability to mutate the data is a side-effect of this. Instead, the fundamental type for shared mutable access is the `*mut` pointer. If you need a lifetime-aware version, then you must write your own wrapper struct over a pointer, and you must uphold that lifetime manually, since the whole lifetime system depends on new mutable accesses invalidating old `&mut` references.

**Comment by CeleritasCelery** [comment]
Touche, you convinced me that `from_raw` should be `unsafe`. 

> Also, I've been looking at the rest of the codebase, and it's difficult to determine what an actual soundness bug should look like.

Reading your comments made me realize the code really needs to be refactored into `core` and `non-core` parts. The interface to the core should be sound. But right now it is too fuzzy where the "safe" API starts and ends. core is `src/arena/`, `src/object/`, and `src/symbol.rs`, and `src/cons/`. The rest is un-core. But the distinction should be clearer. 

> many of the unsafe parts depend on clever invariant with few to no comments explaining why they should hold.

I need to comment the unsafe code better. I have also created the [unsound? label](https://github.com/CeleritasCelery/rune/labels/unsound%3F) on Github where I point to some code with tricky invariants and try and explain why I think it is sound. Hoping that people can point out flaws in my reasoning or implementation. But that is not a replacement for good SAFETY comments.

 > In your blog post, you were wondering if there could be an AliasCell that allowed shared mutable access through &mut references. However, such an AliasCell has always been and will always be UB to use.

`AliasCell` would need language support just like `UnsafeCell`. Essentially it would allow you to read a `&mut T` from a immutable reference/pointer. This would effectively remove the `noalias` annotation in LLVM (That is exactly what the lang team hack does). This would enable my use case as well as self-referential and intrusive data structures. You are correct though that this could never be implemented in a library, it would have to be part of the language.
