### ISSUE TITLE
Publish `rune` documentation online

### ISSUE THREAD

**Issue by Qkessler** [CeleritasCelery/rune#48]
## What should be done?

Publish a github.io page with the Cargo doc documentation from Rune or alternatively find a way to publish the docs without the crate being published to crates.io. It's not currently published and there are naming conflicts if we were to publish it as is (don't think this is something we should look into now)
​
## Why this task should be completed?
​I have seen other crates / languages do that as well (see more details section), which makes the documentation easily consumable, not only directly in the code. That simplifies checking the documentation, as one would not need to do: `cargo doc --workspace --no-deps` to get all the crates documented.

## Acceptance Criteria
- You have searched through alternatives to publish the cargo doc documentation online.
- If the suggested solution is the right one, publish a github.io page with the `cargo doc --workspace --no-deps` behaviour. 
- The github page should be built with CI, so whenever a new commit happens, we don't need to manually publish the index.html pages. Create a job for it, to run on pushes to `master`, **no need to run it on PRs**.

## Where can I find more details?
- Nice example, crate called `rune` (yeah, right): https://github.com/rune-rs/rune/blob/main/.github/workflows/site.yml
- Better example, the `tracing` crate: https://tracing-rs.netlify.app/tracing/
- Our current CI documentation: https://github.com/CeleritasCelery/rune/blob/master/.github/DOCS.md

## Who are the POCs/stakeholders?
- @Qkessler
- @CeleritasCelery

**Comment by CeleritasCelery** [comment]
I think this could be really valuable. I will need to look into how to set that up. Relatedly, I am not super attached to the name “rune”. If there is some name that works better we could call it that. Ideally something that makes it clear it is an Emacsen (similar to how neovim makes its roots in vim clear).

**Comment by Qkessler** [comment]
Yeah, let's think on names, although I'm kinda getting attached to `rune`. I feel like the whole acronym for Emacs packages and emacs-related projects is something really into the Emacs Culture. I feel like "Rust Under Emacs" really sums up the project.

I think I know how to set it up. I see this issue as low hanging fruit that I was hoping other contributors (maybe someone starting with the project) can pick up and deliver. Probably we can do a call for contributors, what do you think?

**Comment by CeleritasCelery** [comment]
Before we call for contributors I would like to have at least the following things done:

1. Core refactor done
2. Documentation published
3. Through documentation of core structures
4. Ability to test built in functions against GNU Emacs

my expectation is that the easiest thing for new contributors will be to implement a new `defun`. Ideally we could create a list of all the ones that are yet to be done. But in order to do that we need to make it clear how to actual code it up. Many of the 1500 Emacs built in function are standalone and easy to write. Some will require more work though.

another easy thing is to look at the “Todo”s in the code and fix those. We could even turn them into issues.

**Comment by Qkessler** [comment]
Took the issue myself, as I was able to set it up and worked with Netlify in the past. You can see how it works on https://rune-rs.netlify.app. I'll publish a PR! 

After that, we need to work on actually making the documentation better! There are lots of stuff documented currently, but if you see the page, getting to them is pretty rough (some private modules, all the generated __subr functions and more).
