### ISSUE TITLE
Unable to compile on NixOS

### ISSUE THREAD

**Issue by bhankas** [CeleritasCelery/rune#86]
This is by all likelihood caused due to unusualness of NixOS, but these issues tend to shine light on lack of hermeticity in build process. 

The short version:

```bash
~/g/rune master 13.2s | 101 ❱ RUST_BACKTRACE=full cargo run --profile=release -- --load --repl
   Compiling tikv-jemalloc-sys v0.6.0+5.3.0-1-ge13ca993e8ccb9ba9847cc330696e02839f328f7
error: failed to run custom build command for `tikv-jemalloc-sys v0.6.0+5.3.0-1-ge13ca993e8ccb9ba9847cc330696e02839f328f7`
```

Full command output with `RUST_BACKTRACE=full` attached. 

I was just trying to explore and by no means a Rust expert (I'm barely at first few chapters in the book), but am happy to help out any way I can.

[rune_log.txt](https://github.com/user-attachments/files/17561626/rune_log.txt)

**Comment by CeleritasCelery** [comment]
From the log it looks likes jemalloc (A C library) failed to build. I don't use Nix, but it would probably be okay to remove jemalloc as a dependency for now. It is really only used as potential performance enhancement, but I have never measured it and we are not a the point where we need to optimizing the allocator anyways.

**Comment by CeleritasCelery** [comment]
Also I have updated the command line examples in the readme. Some of them were outdated. The way to run the repl now is `cargo run --release -- --repl`.

**Comment by bhankas** [comment]
Thanks, I can access repl now.
