### ISSUE TITLE
`(functionp '(lambda ...))` should be `t`

### ISSUE THREAD

**Issue by gudzpoz** [CeleritasCelery/rune#92]
https://github.com/CeleritasCelery/rune/blob/4b5ae64ebfaa0825b8c4dde8c56d35ea32f507df/src/data.rs#L167-L174

I discovered this when debugging a `pcase` issue. Basically `pcase` expects `'(lambda ...)` to be a function, or it might return nil, leading to weird errors elsewhere:

```elisp
(let ((var 'sym)) (pcase () ((let 'sym var) 1)))
;; GNU Emacs => 1
;; Rune => nil
```

**Comment by CeleritasCelery** [comment]
Thanks!
